### ISSUE TITLE
Issues in main.go?

### ISSUE THREAD

**Issue by hartwork** [phayes/freeport#11]
Hi!

Looking at https://github.com/phayes/freeport/blob/95f893ade6f232a5f1511d61735d89b1ae2df543/cmd/freeport/main.go#L12-L16 I found that:
- There is no `os.Exit(..)` here that would prevent `strconv.Itoa` to operate on `0`. Is that intended?
- (Given the flexibility of `fmt.Println`, plain `fmt.Println(port)` should work without `strconv.Itoa`, true?)

Best, Sebastian

**Comment by njkleiner** [comment]
> I found that:
> * There is no `os.Exit(..)` here that would prevent `strconv.Itoa` to operate on `0`. Is that intended?

`log.Fatal(err)` actually calls `os.Exit(1)` under the hood (see https://golang.org/pkg/log/#Fatal).
